### PR TITLE
fixed admin remove route

### PR DESCRIPTION
**Pull request by paulhan221**
@DFurnes  @angaither 

Very minor change, the routes were conflicting so I had to change the route. I thought I had done this in the Admin-fix pull request but I must have undone it before I pushed.

### CODE REVIEW

**Comment by angaither** [comment]
it might be worth turning this into a resource so it has the post and creates set up already

**Comment by DFurnes** [comment]
Yeah, this should definitely be restful.

**Comment by paulhan221** [comment]
@DFurnes @angaither

**Comment by DFurnes** [comment]
Seems good to me. :+1:

**Pull request merged**
